# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceServiceStub(object):
    """Service exposed by each model chunk container.
    The gateway (or the previous chunk in the pipeline) calls Infer()
    to pass an intermediate tensor through the chunk and get the result back.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Infer = channel.unary_unary(
                '/kai.InferenceService/Infer',
                request_serializer=inference__pb2.InferRequest.SerializeToString,
                response_deserializer=inference__pb2.InferResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/kai.InferenceService/HealthCheck',
                request_serializer=inference__pb2.HealthRequest.SerializeToString,
                response_deserializer=inference__pb2.HealthResponse.FromString,
                _registered_method=True)


class InferenceServiceServicer(object):
    """Service exposed by each model chunk container.
    The gateway (or the previous chunk in the pipeline) calls Infer()
    to pass an intermediate tensor through the chunk and get the result back.
    """

    def Infer(self, request, context):
        """Run a forward pass on the chunk and return the output tensor.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Lightweight health / readiness probe.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=inference__pb2.InferRequest.FromString,
                    response_serializer=inference__pb2.InferResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=inference__pb2.HealthRequest.FromString,
                    response_serializer=inference__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kai.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kai.InferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """Service exposed by each model chunk container.
    The gateway (or the previous chunk in the pipeline) calls Infer()
    to pass an intermediate tensor through the chunk and get the result back.
    """

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kai.InferenceService/Infer',
            inference__pb2.InferRequest.SerializeToString,
            inference__pb2.InferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kai.InferenceService/HealthCheck',
            inference__pb2.HealthRequest.SerializeToString,
            inference__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
